### ISSUE TITLE
Apps have no icon size listed 

### ISSUE THREAD

**Issue by jdvp** [d4rken/android-appicondetective#1]
I'm not entirely sure what the expected behavior is but when an app uses a vector drawable, App Icon Detective shows a size of 0x0. Screenshot example (App name is Statistexts): http://imgur.com/Co7TzLu

**Comment by d4rken** [comment]
Should be fixed with: 

https://github.com/d4rken/android-appicondetective/commit/378c0bdb3de5b3580997641fa950e5a5d5915cee
